services:
  postgres:
    image: postgres
    container_name: DocPat
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ahmed
      POSTGRES_DB: DocPatient
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/DocPatient
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ahmed
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  postgres_data :