spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
server:
  port: 8080
  servlet:
    context-path: /api/v1
logging:
  level:
    org.springframework.security: DEBUG